/** Official/common romaji titles for anime story guesses (Latin script). */
export const ANIME_ROMAJI = {
  "one-piece": "Wan Pisu",
  naruto: "Naruto",
  "dragon-ball": "Doragon Boru",
  pokemon: "Poketto Monsutā",
  bleach: "Burīchi",
  "hunter-x-hunter": "Hantā Hantā",
  jojo: "JoJo no Kimyō na Bōken",
  doraemon: "Doraemon",
  "demon-slayer": "Kimetsu no Yaiba",
  "attack-on-titan": "Shingeki no Kyojin",
  "my-hero-academia": "Boku no Hero Academia",
  "jujutsu-kaisen": "Jujutsu Kaisen",
  "death-note": "Desu Nōto",
  "chainsaw-man": "Chenso Man",
  "spy-x-family": "Supai Famirī",
  "sailor-moon": "Bishōjo Senshi Sērā Mūn",
  evangelion: "Shinseiki Evangerion",
  "cowboy-bebop": "Kaubōi Bibappu",
  "fma-brotherhood": "Hagane no Renkinjutsushi",
  "sword-art-online": "Sōdo Āto Onrain",
  "tokyo-ghoul": "Tōkyō Gūru",
  "spirited-away": "Sen to Chihiro no Kamikakushi",
  totoro: "Tonari no Totoro",
  "howls-moving-castle": "Hauru no Ugoku Shiro",
  "princess-mononoke": "Mononoke Hime",
  "your-name": "Kimi no Na wa",
  akira: "Akira",
  "ghost-in-the-shell": "Kōkaku Kidōtai",
  "slam-dunk": "Suramu Danku",
  "detective-conan": "Meitantei Konan",
  "digimon-adventure": "Dejimon Adobenchā",
  "yu-gi-oh": "Yū Gi Ō",
  "captain-tsubasa": "Kyaputen Tsubasa",
  gintama: "Gintama",
  "code-geass": "Kōdo Giasu",
  "one-punch-man": "Wanpanman",
  "mob-psycho": "Mobu Saiko Hyaku",
  haikyu: "Haikyū",
  "dragon-ball-super": "Doragon Boru Sūpā",
  nausicaa: "Kaze no Tani no Naushika",
  "kiki-delivery-service": "Majo no Takkyūbin",
  "castle-in-the-sky": "Tenkū no Shiro Rapyuta",
  "kurokos-basketball": "Kuroko no Basuke",
  "steins-gate": "Shutainzu Gēto",
  "re-zero": "Re:Zero",
  "black-clover": "Burakku Kurōbā",
  "fairy-tail": "Fearī Teiru",
  "vinland-saga": "Vinland Saga",
  "blue-lock": "Burū Rokku",
  frieren: "Sōsō no Frieren",
  "solo-leveling": "Ore dake Level Up na Ken",
  ponyo: "Gake no Ue no Ponyo",
  "initial-d": "Inisharu Dī",
  "madoka-magica": "Mahō Shōjo Madoka Magika",
  monogatari: "Monogatari Series",
  "psycho-pass": "Saiko Pasu",
  gundam: "Kidō Senshi Gandamu",
  "bocchi-the-rock": "Bocchi the Rock",
  "oshi-no-ko": "Oshi no Ko",
  "hells-paradise": "Jigokuraku",
  "dr-stone": "Dr. Stone",
  "fire-force": "En'en no Shōbōtai",
  "tokyo-revengers": "Tōkyō Ribenjāzu",
  "made-in-abyss": "Meido in Abyss",
  "my-dress-up-darling": "Sono Bisque Doll wa Koi o Suru",
  "soul-eater": "Souru Ītā",
  "black-butler": "Kuroshitsuji",
  noragami: "Noragami",
  durarara: "Durarara",
  bakuman: "Bakuman",
  parasyte: "Kiseijū",
  "ergo-proxy": "Ergo Proxy",
  flcl: "Furi Kuri",
  "kill-la-kill": "Kill la Kill",
  promare: "Promare",
  "weathering-with-you": "Tenki no Ko",
  "a-silent-voice": "Koe no Katachi",
  "perfect-blue": "Pāfekuto Burū",
  paprika: "Papurika",
  "violet-evergarden": "Vaioretto Evāgāden",
  "banana-fish": "Banana Fish",
  given: "Given",
  beastars: "Beastars",
  "odd-taxi": "Odd Taxi",
  mashle: "Mashle",
  "undead-unluck": "Undead Unluck",
  dandadan: "Dandadan",
  hellsing: "Hellsing",
  trigun: "Trigun",
  "samurai-champloo": "Samurai Champloo",
  "serial-experiments-lain": "Serial Experiments Lain",
  "cardcaptor-sakura": "Kādokyaputā Sakura",
  ranma: "Ranma Nibun no Ichi",
  inuyasha: "Inuyasha",
  "rurouni-kenshin": "Rurouni Kenshin",
  "bleach-thousand-year": "Bleach: Sennen Kessen-hen",
};
